### PR TITLE
Add a few packages I'd missed earlier

### PR DESCRIPTION
**Pull request by fperez**
- cartopy: key for some common operations on geophysical data
- ipympl: interactive matplotlib (widget) backend
- JupyterLab GeoJSON extension: display GeoJSON files as maps.
- JupyterBook (and related packages): for participants to learn how to directly publish repos from their hub as websites.
- nbdime: improved version control for notebooks

### CODE REVIEW

**Comment by fperez** [comment]
Leaving this here for reference - I tried using the binder link above to make sure this was OK before merging it, but right now something isn't working right on the binder end:

```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerlpnsekwx'...
HEAD is now at ea49c26 Add a few packages I'd missed earlier
Using DockerBuildPack builder
Step 1/10 : FROM public.ecr.aws/q3h7b4o8/helio-notebook-py:v0.13_7
write /var/lib/docker/tmp/GetImageBlob875577480: no space left on deviceBuilt image, launching...
Failed to connect to event stream
```

I gotta crash for now, but if nobody has other suggestions, I'll merge the PR tomorrow and play with it, I think it's pretty innocuous (famous last words) :)

**Comment by fperez** [comment]
Ok, merging this, will test later the image in the configurator. Gotta ride up to the workshop now :)

**Comment by yuvipanda** [comment]
@fperez i updated the configurator to use this, the packages you added (+ jupyterlab-favorites) are there. Turns out I needed to use mamba, not conda

**Comment by fperez** [comment]
Thx so much @yuvipanda! I just got to my room and have to finish my talk for tomorrow, so any time saved is much appreciated :)

**Comment by yuvipanda** [comment]
@fperez feel free to ping me on slack for anything too

**Pull request merged**
